apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: flask-httpproxy
  namespace: flask
spec:
  virtualhost:
    fqdn: mohvah-flask.gotlab.local
    tls:
      passthrough: true
  routes:
    - conditions:
      - prefix: /
      services:
        - name: flask-service
          port: 80
