apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: test
  namespace: flask 
spec:
  virtualhost:
    fqdn: mohvah-flask.gotlab.local
  routes:
    - conditions:
      - prefix: /
      services:
        - name: flask-service
          port: 80
